---
title: Test Filter Mermaid
---
flowchart TD

    classDef orange fill:#f96


    subgraph A["Graph A"]
        toto[Le toto]
        tete[Le tete]
    end
    class toto orange

    subgraph B["Graph B"]
        tata[Le tata]
        titi[Le titi]
    end

    subgraph C["Graph C"]
        onch[Onch]
        truc[Le Truc]
    end

    toto --> tata
    toto --> titi
    titi --> tata
    tete =====> titi
    onch <--> truc
