---
title: Test Filter Mermaid
---
flowchart TD

    classDef orange fill:#f96


    subgraph A["Graph A"]
        toto[(Le toto)]
        tyty([Le tyty])
        tete[/Le tete/]
    end
    class toto orange

    subgraph B["Graph B"]
        tata{Le tata}
        titi(((Le titi)))
    end

    subgraph C["Graph C"]
        onch[/Onch\]
        truc[\Le Truc/]
        ouf{{Le Ouf}}
        dingue>Le Dingue]
        rigolo[[Le Rigolo]]
    end

    toto --> tata
    toto --> titi
    titi --> tata
    tete =====> titi
    onch <--> truc

